### ISSUE TITLE
Not all alba asds are claimed as backend_disks and can be used for other roles

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework-alba-plugin#169]
We've observed this on a environment: http://i63.tinypic.com/or07id.png

It seems like not all alba disks are "seen" as backend disks. This means we could change/add roles to the backend disks. This should not be possible.

**Comment by khenderick** [comment]
The cause of this issue is the fact that the Backend disks are handled differently from the StorageRouter disks. They are discovered differently, and their path can be different. E.g. a disk in the Backend cannot be identified by it's wwn, but for the StorageRouter disks, it can. And this path is the identifier with which the Backend role is linked.

**Comment by khenderick** [comment]
In an ideal world, we would use wwns all the time, but it isn't available on vmware envs.

**Comment by khenderick** [comment]
@wimpers, can we re-validate what disks can be used for backends and/or roles? I'd like to get both disk related code more in line so this ticket can be resolved.

Currently:
* Roles: basically udev reported devices with type ```disk``` or a devicename that contains ```loop```, ```nvme``` or ```md```.
* Backend: must be in ```/dev/disk/by-id/```, starting wtih ```scsi-```, ```ata-```, ```virtio-``` or ```nvme-``` pointing to ```/dev/[sv]d*``` or ```/dev/nvme*```.

**Comment by khenderick** [comment]
After discussions with @wimpers, we want to allow basically every block device that can be found, it's up to the customer to decide whether a disk would be a good choice or not. This means we can bring the implementations more in line and thus in theory have the same identifier for these code paths, which in turn should solve the reported issue.

**Comment by pploegaert** [comment]
@khenderick: we now install also ovs on kvm/qemu, so if possible pls include vd* too ...

**Comment by khenderick** [comment]
Removed question label, apparently I already posted the answer of the discussion.

**Comment by JeffreyDevloo** [comment]
Perhaps we shouldn't use the diskname as an identifier as these names aren't persistent.

**Comment by khenderick** [comment]
Depending on the implementation of openvstorage/framework#792 and the implementation of the same logic in the openvstorage/asd-manager repo. This will result in both sides having the same code, which in turn should make this ticket obsolete.

**Comment by kvanhijf** [comment]
Most likely fixed by https://github.com/openvstorage/framework/issues/792

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup latest cluster
- Configured latest cluster
- Evaluated if backend disks could be configured with roles (code wise and GUI wise)

### Output
#### GUI:
![selection_066](https://cloud.githubusercontent.com/assets/17570109/20478478/8f3a639c-afda-11e6-9b91-d58a9b27c1e7.png)

#### API
Code:
```
# Copyright (C) 2016 iNuron NV
#
# This file is part of Open vStorage Open Source Edition (OSE),
# as available from
#
#      http://www.openvstorage.org and
#      http://www.openvstorage.com.
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License v3 (GNU AGPLv3)
# as published by the Free Software Foundation, in version 3 as it comes
# in the LICENSE.txt file of the Open vStorage OSE distribution.
#
# Open vStorage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY of any kind.
from ci.helpers.api import OVSClient
from ci.helpers.roles import RoleHelper
from ci.helpers.storagerouter import StoragerouterHelper


class ConfigureTest(object):

    @staticmethod
    def test():
        # Current configuration uses sda, sdb and sdc for backend
        ip = '10.100.199.151'
        roles = ['WRITE']
        diskname = 'sda'
        api = OVSClient(ip, 'admin', 'admin')
        ConfigureTest.add_disk_role(ip, diskname, roles, api)
        # Expecting an error to occur
        print 'Test failed'

    @staticmethod
    def add_disk_role(ip, diskname, roles, api, min_size=2):
        """
        Partition and adds roles to a disk

        :param ip: storagerouter ip where the disk is located
        :type ip: str
        :param diskname: shortname of a disk (e.g. sdb)
        :type diskname: str
        :param roles: list of roles you want to add to the disk
        :type roles: list
        :param api: specify a valid api connection to the setup
        :type api: ci.helpers.api.OVSClient
        :param min_size: minimum total_partition_size that is required to allocate the disk role
        :type min_size: int
        :param config: configuration file
        :type config: dict
        :return:
        """

        # Fetch information
        storagerouter_guid = StoragerouterHelper.get_storagerouter_guid_by_ip(ip)
        disk = StoragerouterHelper.get_disk_by_ip(ip, diskname)
        # Check if there are any partitions on the disk, if so check if there is enough space
        unused_partitions = []
        if len(disk.partitions) > 0:
            total_partition_size = 0
            for partition in disk.partitions:
                total_partition_size += partition.size
                # Check if the partition is in use - could possibly write role on unused partition
                # if partition.mountpoint is None:
                    # Means no output -> partition not mounted
                    # @Todo support partitions that are not sequentional
                unused_partitions.append(partition)

            # Elect biggest unused partition as potential candidate
            biggest_unused_partition = None
            if len(unused_partitions) > 0:
                # Sort the list based on size
                unused_partitions.sort(key=lambda x: x.size, reverse=True)
                biggest_unused_partition = unused_partitions[0]
            if ((disk.size-total_partition_size)/1024**3) > min_size:
                # disk is still large enough, let the partitioning begin and apply some roles!
                RoleHelper._configure_disk(storagerouter_guid=storagerouter_guid, disk_guid=disk.guid, offset=total_partition_size+1,
                                          size=(disk.size-total_partition_size)-1, roles=roles, api=api)
            elif biggest_unused_partition is not None and (biggest_unused_partition.size/1024**3) > min_size:
                RoleHelper._configure_disk(storagerouter_guid=storagerouter_guid, disk_guid=disk.guid, offset=biggest_unused_partition.offset,
                                          size=biggest_unused_partition.size, roles=roles, api=api, partition_guid=biggest_unused_partition.guid)
            else:
                # disk is too small
                raise RuntimeError("Disk `{0}` on node `{1}` is too small for role(s) `{2}`, min. total_partition_size is `{3}`"
                                   .format(diskname, ip, roles, min_size))
        else:
            # there are no partitions on the disk, go nuke it!
            RoleHelper._configure_disk(storagerouter_guid, disk.guid, 0, disk.size, roles, api)

if __name__ == "__main__":
    ConfigureTest.test()
```
Output:
```
2016-11-21 13:39:25 41200 +0100 - ovs-node-1 - 25015/140532161955584 - setup/ci_role_helper - 0 - INFO - Adjusting disk `3984a040-7130-49eb-a80b-468b9a25b7c5` should have succeeded on storagerouter `32783fe3-b2df-471a-9db5-41419e07efa1`
Test failed
```

### Test result
Test failed. The call has been blocked on GUI but can still happen via API.

### Packages
-openvstorage                         2.7.6-rev.4320.8c4fb99- amd64                   openvStorage
-openvstorage-backend                 1.7.6-rev.817.91abb7c-1 amd64                   openvStorage Backend plugin
-openvstorage-backend-core            1.7.6-rev.817.91abb7c-1 amd64                   openvStorage Backend plugin core
-openvstorage-backend-webapps         1.7.6-rev.817.91abb7c-1 amd64                   openvStorage Backend plugin Web Applications
-openvstorage-core                    2.7.6-rev.4320.8c4fb99- amd64                   openvStorage core
-openvstorage-hc                      1.7.6-rev.817.91abb7c-1 amd64                   openvStorage Backend plugin HyperConverged
-openvstorage-sdm                     1.6.6-rev.445.4216f7e-1 amd64                   Open vStorage Backend ASD Manager
-openvstorage-webapps                 2.7.6-rev.4320.8c4fb99- amd64                   openvStorage Web Applications
